"""empty message

Revision ID: 80966de3742e
Revises: 
Create Date: 2018-04-21 15:47:38.423868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80966de3742e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=100), nullable=True),
    sa.Column('movie_img', sa.String(length=500), nullable=True),
    sa.Column('movie_url', sa.String(length=500), nullable=True),
    sa.Column('movie_type', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(length=100), nullable=True),
    sa.Column('movie_img', sa.String(length=500), nullable=True),
    sa.Column('movie_url', sa.String(length=500), nullable=True),
    sa.Column('movie_type', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_img'),
    sa.UniqueConstraint('movie_name'),
    sa.UniqueConstraint('movie_type'),
    sa.UniqueConstraint('movie_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_test')
    op.drop_table('movie')
    # ### end Alembic commands ###
